[package]
name = "streamrs"
version = "0.2.0"
edition = "2024"

[dependencies]
chrono = "0.4"
hidapi = "2.6.4"
image = "0.25.9"
resvg = "0.45"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"

[profile.release]
strip = true
