[package]
name = "streamrs"
version = "0.2.7"
edition = "2024"

[dependencies]
chrono = "0.4.43"
hidapi = "2.6.4"
image = "0.25.9"
resvg = "0.45.1"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.8.23"

[profile.release]
strip = true
